export const OPEN_FILTERS_DRAWER = 'OPEN_FILTERS_DRAWER';
export const CLOSE_FILTERS_DRAWER = 'CLOSE_FILTERS_DRAWER';
export const FETCH_FILTERS = 'FETCH_FILTERS';
export const SELECT_FILTER = 'SELECT_FILTER';
export const REMOVE_FILTER = 'DELETE_FILTER';
export const TOGGLE_FILTER_GROUP = 'TOGGLE_FILTER_GROUP';
export const GET_SELECTED_OPTION = 'GET_SELECTED_OPTION';
